# Parametros iniciais e fundamentais para o funcionamento
baseURL = "http://example.org/"
languageCode = "pt-br"
title = "Tchelinux"
theme = "tuz"

# Parametros customizados
[params]
  description = "Grupo de Usuários de Software Livre do Rio Grande do Sul"
  grupoGoogle = ""
  facebook = ""
  gplus = ""
  twitter = ""
  

# Configuração dos links permanentes
[permalinks]
  paginas = "/:filename"

# Menu principal do site
[[menu.main]]
  name = "Sobre"
  identifier = "sobre"
  url = "/#/"
  weight = 1

[[menu.main]]
  name = "Participe"
  identifier = "participe"
  url = "/#/"
  weight = 3
